# Generated by Django 3.2.12 on 2022-05-07 08:50

import BaseOrm
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.SmallIntegerField(verbose_name='消息标识1,方便查询,群发还是单聊')),
                ('data_type', models.SmallIntegerField(null=True, verbose_name='消息标识2，方便查询，发送文件的属性')),
                ('txt', models.TextField(verbose_name='消息本身')),
                ('file', models.FileField(upload_to='file/', verbose_name='文件路径')),
                ('create_date', models.DateTimeField(verbose_name='消息时间')),
                ('client_id', models.BigIntegerField(verbose_name='客户端消息id')),
                ('is_read', models.IntegerField(verbose_name='已读未读 0-未读 1-已读')),
                ('is_send', models.IntegerField(verbose_name='是否已经发送 0-未发送 1-已发送')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='User.group', verbose_name='接收群id')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send', to='User.user', verbose_name='发送者用户id')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to', to='User.user', verbose_name='接收者用户id')),
            ],
            options={
                'verbose_name_plural': '消息记录表',
                'db_table': 'chat_msg',
            },
            bases=(BaseOrm.BaseModel, models.Model),
        ),
    ]
